### PR TITLE
Use svg icons and update manifest

### PR DESCRIPTION
**Pull request by smac89**
Original: https://github.com/jc3213/download_with_aria2-firefox/pull/12

The regular png icons look terrible with the right-click context menu on FF. The dark on dark is difficult to see.

This PR converted the png's to svg to produce two files <sup>1</sup>:
- One for light themes
- Another for dark themes

The result should be a more uniformed look on FF between light and dark themed browsers.

I did not test for Chrome because I don't use Chrome, but the result should be similar I believe.

---
1. _icons were created with GIMP and inkscape_

### CODE REVIEW

**Comment by jc3213** [comment]
The icon under white theme has not been fixed, and the popup window is also broken.
broken icon and popup

**Comment by smac89** [comment]
Ok so I think a good compromise would be to make the icon grey, i.e. not too dark, not too light otherwise, it will work in one and not the other.

As for the weird behavior with the popup, that's because I set `browser_style:true` in the manifest. 
I added a fix for that. See this [link](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Browser_styles) to find other interesting style classes that FF provides for making the UI fit the browser.

**Comment by smac89** [comment]
Don't mind my commits. Just trying to squash everything I did into one commit, but I think after you committed, I've just been unable to get this right. I hope you don't mind multiple commits

**Comment by smac89** [comment]
if you have any further issues with this PR, let me know. Otherwise, if you want to merge, just ping me here and I will resolve any further conflicts

**Comment by gbcox** [comment]
The new icon is quite an improvement, I like the blue color - but the down arrow is so small now on the toolbar it looks a bit like a handle on a dustpan.  
image

**Pull request closed without merging**
